name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'profile'
        required: true
        type: choice
        options:
          - login
          - order
          - checkOrder
          - headed

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: |
        if [ "${{ inputs.profile }}" == "headed" ]; then
          npx wdio run wdio.conf.js --headless false;
        else
          npm run ${{ inputs.profile }};
        fi
      env:
        CI: true
